site:
  title: Payara Community Documentation
  start_page: docs::deployment-groups.adoc
content:
  sources:
    - url: .
      start_path: docs
      branches: HEAD
    - url: .
      start_path: community/docs
      branches: HEAD
asciidoc:
  attributes:
    attribute-missing: 'skip'
ui:
  bundle:
    url: https://github.com/payara/antora-ui-default/raw/master/build/ui-bundle.zip
    snapshot: true
runtime:
  fetch: true
output:
    dir: ./build/community/html
