site:
  title: Payara Community Documentation
  start_page: docs::Overview.adoc
content:
  sources:
    - url: .
      start_path: docs
      branches: HEAD
    - url: https://github.com/AlanRoth/Payara-Documentation.git
      start_path: community/docs
      branches: [ main ]
asciidoc:
  attributes:
    attribute-missing: 'skip'
ui:
  bundle:
    url: https://github.com/payara/antora-ui-default/raw/master/build/ui-bundle.zip
    snapshot: true
runtime:
  fetch: true
output:
  dir: ./build/html
